# Generated by Django 5.0.2 on 2024-03-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.TextField()),
                ('office', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('startDate', models.DateField()),
                ('salary', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
    ]
